# Permalinks
permalink:           pretty

# Setup
title:               SkylerL2
tagline:             Data Science
url:                 http://skylerl2.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Skyler Lehto
  url:               
  email:             

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/skylerl2

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
